name: Sync Peloton to Garmin
on:
  schedule:
    - cron: '* */2 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: philosowaffle/peloton-to-garmin:console-stable
    steps:
      - name: Run Peloton to Garmin Sync
        env:
          PELOTON_USERNAME: ${{ secrets.PELOTON_USERNAME }}
          PELOTON_PASSWORD: ${{ secrets.PELOTON_PASSWORD }}
          GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          OUTPUT_DIR: /github/workspace/output  # Set inside container
        run: |
          mkdir -p "$OUTPUT_DIR"
          dotnet /app/PelotonToGarminConsole.dll --peloton-username "$PELOTON_USERNAME" --peloton-password "$PELOTON_PASSWORD" --garmin-username "$GARMIN_USERNAME" --garmin-password "$GARMIN_PASSWORD" --output "$OUTPUT_DIR"
      - name: Zip Output Files
        run: zip -r output.zip "$OUTPUT_DIR"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FitFiles
          path: output.zip
          retention-days: 5
