name: Sync Peloton to Garmin
on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
jobs:
  sync-peloton-to-garmin:
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: ./output
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Changed from 6.0.x to match global.json
      - name: Create Output Directory
        run: mkdir -p "$OUTPUT_DIR"
      - name: Sync Peloton workouts
        env:
          PELOTON_USERNAME: ${{ secrets.PELOTON_USERNAME }}
          PELOTON_PASSWORD: ${{ secrets.PELOTON_PASSWORD }}
          GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
        run: dotnet run --project ./src/PelotonToGarminConsole -- --output "$OUTPUT_DIR"
      - name: Zip Output Files
        run: zip -r output.zip "$OUTPUT_DIR"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FitFiles
          path: output.zip
          retention-days: 5
